name: Unit Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.5'
      - uses: actions/cache@v2
        with:
          path: ~/vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile.lock') }}
      - name: setup bundler & shellcheck
        run: |
          gem install bundler -v 1.17.3
          bundle config path ~/vendor/bundle
          apt-get update
          apt-get install shellcheck
      - name: install gems
        run: bundle install
      - name: test
        run: bundle exec rake test
      - name: shellcheck
        run: shellcheck hooks/*
