name: Unit Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Setup Ruby using Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7.1"
          bundler-cache: true
          bundler: "2.1.4"

      - name: Install shellcheck
        run: |
          sudo apt-get update
          sudo apt-get install shellcheck

      - name: Install gems
        run: bundle install

      - name: Test
        run: bundle exec rake test

      - name: Shellcheck
        run: shellcheck hooks/*
